# ASSETS FOR THE INSTALLER

# Foreground Colors
export BLACK='\e[30m'
export RED='\e[31m'
export GREEN='\e[32m'
export YELLOW='\e[33m'
export BLUE='\e[34m'
export MAGENTA='\e[35m'
export CYAN='\e[36m'
export LGRAY='\e[37m'
export GRAY='\e[90m'
export LRED='\e[91m'
export LGREEN='\e[92m'
export LYELLOW='\e[93m'
export LBLUE='\e[94m'
export LMAGENTA='\e[95m'
export LCYAN='\e[96m'
export WHITE='\e[97m'
export RESET='\e[0m'
